title: Notes
description: >- # this means to ignore newlines until "baseurl:"
  A note is something that you write down to remind yourself of something.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wangtiga.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Path of site resources
img: /assets/img
css: /assets/css

## Docs: https://pages.github.com/versions/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

# default layout of the articles in _posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

disqus: wangtiga
email:  wangtiga@gmail.com

socials:
- name: github
  url: https://github.com/wangtiga


nav:
- name: Notes
  path: /
- name: Preview
  path: /pages/preview.html
- name: About
  path: /pages/about.html

collections:
  previews:
    output: true


